# ===========================================================================
# CMAKE-BUILD CONFIGURATION: cmake-build.config.yaml
# ===========================================================================
# PROJECT: cmake-build/examples/
# DESCRIPTION:
#   * Specifies one (or more) CMake projects to build.
#   * Simplifies CMake project setup by providing pre-canned recipes
#     for the build-configurations, cmake-toolchains, cmake-generators, etc.
#   * Simplifies usage of multiple cmake-toolchains
#   * Simplifies usage of multiple cmake-generators
#
# SEE ALSO:
#   * https://github.com/jenisys/cmake-build
# ===========================================================================

cmake_generator: ninja
# MAYBE: cmake_toolchain: cmake/toolchain/XXX.cmake
build_dir_schema: "build.{BUILD_CONFIG}"

build_config_aliases:
  default: debug
  all:
    - debug
    - release

build_configs:
  - debug:
    cmake_build_type: Debug
    # MAYBE: cmake_toolchain: cmake/toolchain/XXX.cmake
    # cmake_generator:
    # cmake_defines:
    # cmake_args:

  - release:
    cmake_build_type: MinSizeRel

projects:
  - library_hello
  - program_hello
